#!/usr/bin/env python3
"""
Convert EGA graphics files to C array declarations.
"""

import os
import sys
from pathlib import Path

def ega_filename_to_c_name(filename):
    """Convert EGA filename to C variable name."""
    name = filename.replace('.ega', '').replace('-', '_')
    return f"sprite_{name}"

def generate_c_comment(filename, size):
    """Generate descriptive comment for the sprite."""
    # Determine dimensions from filename or size
    if '16x32m' in filename:
        dims = '16x32'
    elif '16x16m' in filename:
        dims = '16x16'
    elif '16x8m' in filename:
        dims = '16x8'
    elif '8x16' in filename:
        dims = '8x16'
    elif '128x48' in filename:
        dims = '128x48'
    elif '320x200' in filename:
        dims = '320x200'
    else:
        dims = 'unknown'
    
    # Clean up filename for description
    desc = filename.replace('.ega', '').replace('_', ' ').replace('-', ' ')
    
    return f"""/*
 * {ega_filename_to_c_name(filename)} - {desc} sprite ({dims})
 * 
 * Format: EGA planar (4 planes) + mask
 * Source: reference/disassembly/graphics/{filename}
 */"""

def read_ega_file(filepath):
    """Read EGA file and return byte array."""
    with open(filepath, 'rb') as f:
        return f.read()

def format_byte_array(data):
    """Format byte array as C array initializer."""
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f"    {hex_bytes}")
    return ',\n'.join(lines)

def generate_c_array(filename, data):
    """Generate complete C array definition."""
    c_name = ega_filename_to_c_name(filename)
    size = len(data)
    comment = generate_c_comment(filename, size)
    formatted_data = format_byte_array(data)
    
    return f"""{comment}
const uint8_t {c_name}[{size}] = {{
{formatted_data}
}};
"""

def generate_header_declaration(filename, size):
    """Generate header file declaration."""
    c_name = ega_filename_to_c_name(filename)
    return f"extern const uint8_t {c_name}[{size}];"

def main():
    script_dir = Path(__file__).parent
    graphics_dir = script_dir / 'reference' / 'disassembly' / 'graphics'
    
    if not graphics_dir.exists():
        print(f"Error: Graphics directory not found: {graphics_dir}")
        return 1
    
    # Get all EGA files (excluding the two already done)
    skip_files = {'life_icon_bright_16x16m.ega', 'life_icon_dark_16x16m.ega'}
    ega_files = sorted([f for f in graphics_dir.glob('*.ega') if f.name not in skip_files])
    
    print(f"Found {len(ega_files)} EGA files to convert")
    
    # Generate C source
    c_arrays = []
    h_declarations = []
    
    for ega_file in ega_files:
        data = read_ega_file(ega_file)
        c_arrays.append(generate_c_array(ega_file.name, data))
        h_declarations.append(generate_header_declaration(ega_file.name, len(data)))
    
    # Write to output files
    output_c = script_dir / 'sprite_data_generated.c'
    output_h = script_dir / 'sprite_data_generated.h'
    
    with open(output_c, 'w') as f:
        f.write("""/*
 * sprite_data_generated.c - Auto-generated sprite graphics data
 * 
 * Generated by convert_ega_to_c.py
 * DO NOT EDIT MANUALLY
 */

#include <stdint.h>

""")
        f.write('\n\n'.join(c_arrays))
    
    with open(output_h, 'w') as f:
        f.write("""/*
 * sprite_data_generated.h - Auto-generated sprite declarations
 * 
 * Generated by convert_ega_to_c.py
 * DO NOT EDIT MANUALLY
 */

#ifndef SPRITE_DATA_GENERATED_H
#define SPRITE_DATA_GENERATED_H

#include <stdint.h>

""")
        f.write('\n'.join(h_declarations))
        f.write('\n\n#endif /* SPRITE_DATA_GENERATED_H */\n')
    
    print(f"Generated {output_c}")
    print(f"Generated {output_h}")
    print(f"Processed {len(ega_files)} sprite files")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
